#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("fiskaltrust.AndroidLauncher.Common.Resource", IsApplication=false)]

namespace fiskaltrust.AndroidLauncher.Common
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public static int ft_notification = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int ft_notification_connected = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int ft_notification_error = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int ft_notification_notconnected = 2130771971;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020000
			public static int app_name = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int hello = 2130837505;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
