trigger:
- master
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  projectFile: fiskaltrust.AndroidLauncher.csproj

steps:
- task: NuGetToolInstaller@1

- task: yavt@1
  inputs:
    pathToVersionJson: 'version.json'
    semverVersion: 'v1'

- task: android-manifest-version@1
  inputs:
    sourcePath: 'src/fiskaltrust.AndroidLauncher/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '$(Build.BuildNumber)'
    printFile: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/$(projectFile)'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    jdkOption: 'JDKVersion'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'fiskaltrust_android.keystore'
    apksignerKeystorePassword: '$(KeystorePassword)'
    apksignerKeystoreAlias: 'fiskaltrust-build'
    apksignerKeyPassword: '$(KeyPassword)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    flattenFolders: true

- powershell: 
    Rename-Item -Path "$(build.artifactStagingDirectory)/eu.fiskaltrust.androidlauncher.apk" -NewName "eu.fiskaltrust.androidlauncher.$(Build.BuildNumber).apk"
    
- task: PublishBuildArtifacts@1
