trigger:
- master
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: yavt@1
  inputs:
    pathToVersionJson: 'version.json'
    semverVersion: 'v1'

- task: android-manifest-version@1
  inputs:
    sourcePath: 'src/fiskaltrust.AndroidLauncher.Http/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '$(Build.BuildNumber)'
    printFile: true
  displayName: Version HTTP Launcher

- task: android-manifest-version@1
  inputs:
    sourcePath: 'src/fiskaltrust.AndroidLauncher.Grpc/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '$(Build.BuildNumber)'
    printFile: true
  displayName: Version gRPC Launcher

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
  displayName: Restore NuGet packages

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/fiskaltrust.AndroidLauncher.Http.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    jdkOption: 'JDKVersion'
  displayName: Build HTTP Launcher
  
- task: XamarinAndroid@1
  inputs:
    projectFile: '**/fiskaltrust.AndroidLauncher.Grpc.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    jdkOption: 'JDKVersion'
  displayName: Build gRPC Launcher

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'fiskaltrust_android.keystore'
    apksignerKeystorePassword: '$(KeystorePassword)'
    apksignerKeystoreAlias: 'fiskaltrust-build'
    apksignerKeyPassword: '$(KeyPassword)'
  displayName: Sign APKs

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    flattenFolders: true
  displayName: Copy APKs to staging directory

- powershell: 
    Rename-Item -Path "$(build.artifactStagingDirectory)/eu.fiskaltrust.androidlauncher.grpc.apk" -NewName "eu.fiskaltrust.androidlauncher.grpc.$(Build.BuildNumber).apk";
    Rename-Item -Path "$(build.artifactStagingDirectory)/eu.fiskaltrust.androidlauncher.http.apk" -NewName "eu.fiskaltrust.androidlauncher.http.$(Build.BuildNumber).apk";
  displayName: Rename APK files
    
- task: PublishBuildArtifacts@1
