parameters:
  subscription: ''
  storage: ''
  package: ''

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)/drop'

- task: AzureFileCopy@6
  displayName: 'Upload to blob storage'
  inputs:
    SourcePath: '$(System.ArtifactsDirectory)/drop/${{ parameters.package }}.*.apk'
    azureSubscription: '${{ parameters.subscription }}'
    Destination: AzureBlob
    storage: ${{ parameters.storage }}
    ContainerName: 'android-packages'

